[versions]
axion-release = "1.21.1"
plugin-publish = "2.0.0"
kotest = "6.1.3"
junit-jupiter = "6.0.2"
test-logger = "4.0.0"
kotlinter = "5.4.2"
detekt = "2.0.0-alpha.2"

[plugins]
plugin-publish = { id = "com.gradle.plugin-publish", version.ref = "plugin-publish" }
axion-release = { id = "pl.allegro.tech.build.axion-release", version.ref = "axion-release" }
test-logger = { id = "com.adarshr.test-logger", version.ref = "test-logger" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
detekt = { id = "dev.detekt", version.ref = "detekt" }

[libraries]
kotest-assertions = { group = "io.kotest", name = "kotest-assertions-core", version.ref = "kotest" }
junit-jupiter-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit-jupiter" }
